# Default application configuration that all configurations inherit from.

exclude: "node_modules/**"

linters:
  EmptyLineBetweenBlocks:
    enabled: false

  HexLength:
    enabled: false

  ImportantRule:
    enabled: false
    # exclude:
    #   - "assets/stylesheets/lib/columns/**"
    #   - "assets/stylesheets/lib/overriders/**"
    #   - "assets/stylesheets/lib/mixins/**"
    #   - "assets/stylesheets/lib/global/**"

  NestingDepth:
    enabled: false

  SelectorDepth:
    enabled: false

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: true

  StringQuotes:
    enabled: true
    style: double_quotes
